name: CI

on:
    push:
        branches: [main]
    pull_request: {}

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: (env) setup
              id: setup
              run:
                  echo "::set-output name=node_version::$(jq -r '.volta.node'
                  package.json)"

            - uses: actions/setup-node@main
              with:
                  node-version: ${{ steps.setup.outputs.node_version }}
                  check-latest: true

            - name: (env) yarn global
              run: |-
                  yarn global bin >> $GITHUB_PATH
                  echo "YARN_CACHE_DIR=$(yarn cache dir)" >> $GITHUB_ENV

            - name: (env) cache
              uses: actions/cache@main
              with:
                  path: ${{ env.YARN_CACHE_DIR }}
                  key:
                      ${{ runner.os }}-node${{ steps.setup.outputs.node_version
                      }}-${{ hashFiles('./yarn.lock') }}

            - name: Install
              run: yarn --frozen-lockfile

            - name: Compile
              run: yarn build

            - name: Type Check
              run: yarn typecheck
